name: Deploy Workspace Backend SQL

on:
  push:
    branches:
      - deploy-sql

jobs:
  deploy-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install PostgreSQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Get changed SQL files
        id: changed_sql_files
        run: |
          git diff --name-status ${{ github.event.before }} ${{ github.sha }} | grep '\.sql$' > changes.txt || true

          grep '^A' changes.txt | cut -f2- > added.txt || true

          echo "added_sql_files<<EOF" >> $GITHUB_OUTPUT
          cat added.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run SQL files on PostgreSQL
        run: |
          if [ ! -s added.txt ]; then
            echo "No new SQL files to run."
            exit 0
          fi
          while read file; do
            echo "Running $file on PostgreSQL..."
            export DB_URL="${{ secrets.DATABASE_URL }}"
            DB_NAME=$(echo "$file" | awk -F'/' '{print $2}')
            if [[ "$DB_URL" =~ /[^/]+$ ]]; then
              DB_URL_WITH_DB=$(echo $DB_URL | sed "s/\/[^/]*$/\/$DB_NAME/")
            else
              DB_URL_WITH_DB="${DB_URL}/$DB_NAME"
            fi
            echo "DB_URL_WITH_DB=$DB_URL_WITH_DB"
            psql "$DB_URL_WITH_DB" -a -f "$file"
          done < added.txt
