name: Deploy Workspace Backend SQL

on:
  push:
    branches:
      - deploy-sql

jobs:
  deploy-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install PostgreSQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Test echo serect key
        run: |
          echo "${{ secrets.DATABASE_URL }}"
